version: '3.5'

services:
  db:
    command: --innodb_use_native_aio=0
    container_name: flask-mysql
    image: mysql
    restart: always
    ports:
      - '8083:3306'
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=password
  backend:
    container_name: flask-backend
    restart: always
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    volumes:
      - ./backend:/app
      - backend-env-cache:/app/backend-env
    environment:
      - FLASK_APP=/app/backend.py
      - FLASK_ENV=development
      - FLASK_DEBUG=true
  client:
    container_name: react-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    volumes:
      - './frontend:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
volumes:
  backend-env-cache: {}
