version: "3.5"

services:
  db:
    container_name: flask-mysql
    image: nithiwatter/cs316-database-repository
    build:
      context: ./mysql/
      dockerfile: Dockerfile
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=Flask_React
