export const SEARCH_PENDING = 'SEARCH_PENDING';
export const SEARCH_FINISHED = 'SEARCH_FINISHED';

export const TOP_50_SWITCH_PAGE = 'TOP_50_SWITCH_PAGE';
export const TOP_50_START_API_REQUEST = 'TOP_50_START_API_REQUEST';
export const TOP_50_FINISHED_API_REQUEST = 'TOP_50_FINISHED_API_REQUEST';

export const DETAILED_ANIME_START_API_REQUEST =
  'DETAILED_ANIME_START_API_REQUEST';
export const DETAILED_ANIME_FINISHED_API_REQUEST =
  'DETAILED_ANIME_FINISHED_API_REQUEST';
export const DETAILED_ANIME_SWITCH_PAGE = 'DETAILED_ANIME_SWITCH_PAGE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const SET_CALLBACK_ROUTE = 'SET_CALLBACK_ROUTE';
