export const SEARCH_PENDING = "SEARCH_PENDING";
export const SEARCH_FINISHED = "SEARCH_FINISHED";

export const TOP_50_SWITCH_PAGE = "TOP_50_SWITCH_PAGE";
export const TOP_50_START_API_REQUEST = "TOP_50_START_API_REQUEST";
export const TOP_50_FINISHED_API_REQUEST = "TOP_50_FINISHED_API_REQUEST";

export const DETAILED_ANIME_START_API_REQUEST =
  "DETAILED_ANIME_START_API_REQUEST";
export const DETAILED_ANIME_FINISHED_API_REQUEST =
  "DETAILED_ANIME_FINISHED_API_REQUEST";
export const DETAILED_ANIME_SWITCH_PAGE = "DETAILED_ANIME_SWITCH_PAGE";
