export const SEARCH_PENDING = "SEARCH_PENDING";
export const SEARCH_FINISHED = "SEARCH_FINISHED";

export const TOP_50_SWITCH_PAGE = "TOP_50_SWITCH_PAGE";
export const TOP_50_FINISHED_API_REQUEST = "TOP_50_FINISHED_API_REQUEST";
